name: Setup, Examples, Notebooks

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Python dependencies from conda-forge
      run: |
        # Set up conda using the preinstalled GHA Miniconda environment
        echo $CONDA/bin >> $GITHUB_PATH
        conda config --add channels conda-forge
        conda config --set channel_priority strict

        # Install test tools
        conda install pip pytest

        # Install python-control dependencies
        conda install numpy matplotlib scipy jupyter
        conda install slycot pmw

    - name: Install from source
      run: pip install .

    - name: Run examples
      run: |
        cd examples
        ./run_examples.sh
        ./run_notebooks.sh
